name: mlflow-workflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - pandas>=1.5.0
    - numpy>=1.23.0
    - scikit-learn>=1.2.0
    - mlflow>=2.8.0
    - joblib>=1.2.0
